name: NekoSuite
main: com.moehoshio.nekosuite.NekoSuitePlugin
version: 0.1.0
softdepend: [Vault]
commands:
  wish:
    description: 祈願系統
    usage: /wish <池名稱> [次數] 或 /wish menu
    permission: nekosuite.wish
  event:
    description: 活動系統
    usage: /event [活動ID] 或 /event menu
    permission: nekosuite.event
  exp:
    description: 經驗銀行
    usage: /exp [menu|deposit|withdraw|pay|exchange]
    permission: nekosuite.exp
  cdk:
    description: 兌換CDK
    usage: /cdk <兌換碼>
    permission: nekosuite.cdk
  buy:
    description: 特權商店
    usage: /buy <類型> <等級> 或 /buy menu
    permission: nekosuite.buy
  mail:
    description: 郵件系統
    usage: /mail [menu|claim|delete] [郵件ID]
    permission: nekosuite.mail
  mailsend:
    description: 發送郵件
    usage: /mailsend <玩家> <主題> [內容]
    permission: nekosuite.mail.send
  mailadmin:
    description: 郵件管理
    usage: /mailadmin <send|template> <參數...>
    permission: nekosuite.mail.admin
  language:
    description: 語言設置
    usage: /language <語言代碼|list|reset>
    permission: nekosuite.language
  nekoreload:
    description: 重載配置
    usage: /nekoreload
    permission: nekosuite.reload
  sgame:
    description: 策略遊戲
    usage: /sgame [menu|status|abandon]
    permission: nekosuite.sgame
  nekonav:
    description: 導航頁面
    usage: /nekonav
    permission: nekosuite.nav
  nekohelp:
    description: 幫助頁面
    usage: /nekohelp
    permission: nekosuite.help
  nekobroadcast:
    description: 公告系統
    usage: /nekobroadcast <訊息>
    permission: nekosuite.broadcast
