name: NekoSuite
main: com.moehoshio.nekosuite.NekoSuitePlugin
version: 0.1.0
softdepend: [Vault]
commands:
  wish:
    description: Execute wish draws
    usage: /wish <pool> [count] or /wish query <pool> or /wish menu
    permission: nekosuite.wish
  wishquery:
    description: Query wish status
    usage: /wishquery <pool>
    permission: nekosuite.wish.query
  wishmenu:
    description: Open wish GUI
    usage: /wishmenu
    permission: nekosuite.wish.menu
  eventcheck:
    description: Check available events
    usage: /eventcheck
    permission: nekosuite.event.check
  eventparticipate:
    description: Participate in an event
    usage: /eventparticipate <eventId>
    permission: nekosuite.event.participate
  event:
    description: Event operations
    usage: /event <check|participate|menu> [eventId]
    permission: nekosuite.event
  eventmenu:
    description: Open event GUI
    usage: /eventmenu
    permission: nekosuite.event.menu
  exp:
    description: Experience account operations
    usage: /exp <balance|save|withdraw|pay|menu|exchange>
    permission: nekosuite.exp
  expmenu:
    description: Open experience GUI
    usage: /expmenu
    permission: nekosuite.exp.menu
  cdk:
    description: Redeem CDK code
    usage: /cdk <code>
    permission: nekosuite.cdk
  buy:
    description: Purchase privileges
    usage: /buy <productId> or /buy menu
    permission: nekosuite.buy
  buymenu:
    description: Open privilege purchase menu
    usage: /buymenu
    permission: nekosuite.buy.menu
  mail:
    description: Mail operations
    usage: /mail <menu|list|claim|delete>
    permission: nekosuite.mail
  mailmenu:
    description: Open mail GUI
    usage: /mailmenu
    permission: nekosuite.mail.menu
  mailsend:
    description: Send mail to a player
    usage: /mailsend <player> <subject> [message]
    permission: nekosuite.mail.send
  mailadmin:
    description: Admin mail commands
    usage: /mailadmin <send|template> <player> <subject|templateId> [content] [commands...]
    permission: nekosuite.mail.admin
  language:
    description: Set preferred language
    usage: /language <code|list|reset>
    permission: nekosuite.language
  nekoreload:
    description: Reload NekoSuite configs
    usage: /nekoreload
    permission: nekosuite.reload
  sgame:
    description: Strategy game commands
    usage: /sgame <start|continue|status|end|abandon|menu>
    permission: nekosuite.sgame
  sgamemenu:
    description: Open strategy game menu
    usage: /sgamemenu
    permission: nekosuite.sgame.menu
