name: NekoSuite
main: com.moehoshio.nekosuite.NekoSuitePlugin
version: 0.1.0
softdepend: [Vault]
commands:
  wish:
    description: 祈願系統
    usage: /wish <池名稱> [次數] 或 /wish menu
    permission: nekosuite.wish
  event:
    description: 活動系統
    usage: /event [活動ID] 或 /event menu
    permission: nekosuite.event
  exp:
    description: 經驗銀行
    usage: /exp [menu|deposit|withdraw|pay|exchange]
    permission: nekosuite.exp
  cdk:
    description: 兌換CDK
    usage: /cdk <兌換碼>
    permission: nekosuite.cdk
  buy:
    description: 特權商店
    usage: /buy <類型> <等級> 或 /buy menu
    permission: nekosuite.buy
  mail:
    description: 郵件系統
    usage: /mail [menu|claim|delete] [郵件ID]
    permission: nekosuite.mail
  mailsend:
    description: 發送郵件
    usage: /mailsend <玩家> <主題> [內容]
    permission: nekosuite.mail.send
  mailadmin:
    description: 郵件管理
    usage: /mailadmin <send|template> <參數...>
    permission: nekosuite.mail.admin
  language:
    description: 語言設置
    usage: /language <語言代碼|list|reset>
    permission: nekosuite.language
  nekoreload:
    description: 重載配置
    usage: /nekoreload
    permission: nekosuite.reload
  sgame:
    description: 策略遊戲
    usage: /sgame [menu|status|abandon]
    permission: nekosuite.sgame
  artifact:
    description: 特別獎勵發放 (僅管理員)
    usage: /artifact list 或 /artifact give <玩家> <物品ID>
    permission: nekosuite.artifact.admin
  announce:
    description: 發送公告
    usage: /announce <訊息>
    permission: nekosuite.announce
  nekomenu:
    description: 主選單/導航頁
    usage: /neko [menu|help]
    permission: nekosuite.menu
    aliases:
      - neko
  nekohelp:
    description: 幫助頁 (已棄用，請使用 /neko help)
    usage: /neko help
    permission: nekosuite.help
  ntp:
    description: 傳送系統
    usage: /ntp <玩家>|accept|deny|toggle|cancel
    permission: nekosuite.tp
  ntpadmin:
    description: 傳送系統管理 (鎖定/解鎖玩家)
    usage: /ntpadmin <lock|unlock|status> <玩家>
    permission: nekosuite.tp.admin
  skill:
    description: 技能系統
    usage: /skill [list|info <技能ID>]
    permission: nekosuite.skill
  ngame:
    description: 小遊戲系統
    usage: /ngame <rtp|arena|fishing|cardbattle|blackjack> [子命令]
    permission: nekosuite.game
    aliases:
      - nekogame
  cardbattle:
    description: 卡牌對決遊戲
    usage: /cardbattle [menu|pve|pvp <玩家>|accept|decline|surrender]
    permission: nekosuite.game.cardbattle
    aliases:
      - cb
  blackjack:
    description: 21點遊戲
    usage: /blackjack [menu|bet <金額>]
    permission: nekosuite.game.blackjack
    aliases:
      - bj
